### ISSUE TITLE
Is this package still maintained for Julia 1.3.1? SMMOptions not defined

### ISSUE THREAD

**Issue by zxjroger** [JulienPascal/SMM.jl#25]
Hi Julien,

I am trying to use your package in Julia 1.3.1.
`] add SMM`

Then following the example https://github.com/JulienPascal/SMM.jl/blob/master/examples/example2dNormalSerial.ipynb

`using SMM`
`using Distributions`
`using DataStructures`
`myProblem = SMMProblem(options = SMMOptions(maxFuncEvals=1000, saveSteps = 1000, globalOptimizer = :dxnes));`

Then, I got error `ERROR: UndefVarError: SMMOptions not defined`.

But if I code `MProb()` as suggested in another version of this package
https://github.com/floswald/SMM.jl
It works. So I wonder which package is the correct one?

**Comment by JulienPascal** [comment]
Hi,

The package is stuck at Julia 0.6.4 for the moment. When I have time, I will make a major update to make it usable on the latest stable version of Julia.

**Comment by JulienPascal** [comment]
Hi,

You can go [here](https://github.com/JulienPascal/MSM.jl)
I have updated the package. It now works on Julia 1.5.
